apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: uk.icr.io/ct-jauninb-tkn-razee/hello-app-razee:7-master-a8c27f37-20200720103424
        ports:
        - containerPort: 8080
