apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: uk.icr.io/ct-jauninb-tkn-razee/hello-app-razee:10-master-aa7fc4f8-20200821131900
        ports:
        - containerPort: 8080
